################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jaricom.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jcapimin.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jcapistd.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jcarith.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jccoefct.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jccolor.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jcdctmgr.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jchuff.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jcinit.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jcmainct.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jcmarker.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jcmaster.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jcomapi.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jcparam.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jcprepct.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jcsample.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jctrans.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jdapimin.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jdapistd.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jdarith.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jdatadst.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jdatasrc.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jdcoefct.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jdcolor.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jddctmgr.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jdhuff.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jdinput.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jdmainct.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jdmarker.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jdmaster.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jdmerge.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jdpostct.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jdsample.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jdtrans.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jerror.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jfdctflt.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jfdctfst.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jfdctint.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jidctflt.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jidctfst.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jidctint.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jmemmgr.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jmemnobs.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jquant1.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jquant2.c \
E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jutils.c 

OBJS += \
./Middlewares/Lib_JPEG/jaricom.o \
./Middlewares/Lib_JPEG/jcapimin.o \
./Middlewares/Lib_JPEG/jcapistd.o \
./Middlewares/Lib_JPEG/jcarith.o \
./Middlewares/Lib_JPEG/jccoefct.o \
./Middlewares/Lib_JPEG/jccolor.o \
./Middlewares/Lib_JPEG/jcdctmgr.o \
./Middlewares/Lib_JPEG/jchuff.o \
./Middlewares/Lib_JPEG/jcinit.o \
./Middlewares/Lib_JPEG/jcmainct.o \
./Middlewares/Lib_JPEG/jcmarker.o \
./Middlewares/Lib_JPEG/jcmaster.o \
./Middlewares/Lib_JPEG/jcomapi.o \
./Middlewares/Lib_JPEG/jcparam.o \
./Middlewares/Lib_JPEG/jcprepct.o \
./Middlewares/Lib_JPEG/jcsample.o \
./Middlewares/Lib_JPEG/jctrans.o \
./Middlewares/Lib_JPEG/jdapimin.o \
./Middlewares/Lib_JPEG/jdapistd.o \
./Middlewares/Lib_JPEG/jdarith.o \
./Middlewares/Lib_JPEG/jdatadst.o \
./Middlewares/Lib_JPEG/jdatasrc.o \
./Middlewares/Lib_JPEG/jdcoefct.o \
./Middlewares/Lib_JPEG/jdcolor.o \
./Middlewares/Lib_JPEG/jddctmgr.o \
./Middlewares/Lib_JPEG/jdhuff.o \
./Middlewares/Lib_JPEG/jdinput.o \
./Middlewares/Lib_JPEG/jdmainct.o \
./Middlewares/Lib_JPEG/jdmarker.o \
./Middlewares/Lib_JPEG/jdmaster.o \
./Middlewares/Lib_JPEG/jdmerge.o \
./Middlewares/Lib_JPEG/jdpostct.o \
./Middlewares/Lib_JPEG/jdsample.o \
./Middlewares/Lib_JPEG/jdtrans.o \
./Middlewares/Lib_JPEG/jerror.o \
./Middlewares/Lib_JPEG/jfdctflt.o \
./Middlewares/Lib_JPEG/jfdctfst.o \
./Middlewares/Lib_JPEG/jfdctint.o \
./Middlewares/Lib_JPEG/jidctflt.o \
./Middlewares/Lib_JPEG/jidctfst.o \
./Middlewares/Lib_JPEG/jidctint.o \
./Middlewares/Lib_JPEG/jmemmgr.o \
./Middlewares/Lib_JPEG/jmemnobs.o \
./Middlewares/Lib_JPEG/jquant1.o \
./Middlewares/Lib_JPEG/jquant2.o \
./Middlewares/Lib_JPEG/jutils.o 

C_DEPS += \
./Middlewares/Lib_JPEG/jaricom.d \
./Middlewares/Lib_JPEG/jcapimin.d \
./Middlewares/Lib_JPEG/jcapistd.d \
./Middlewares/Lib_JPEG/jcarith.d \
./Middlewares/Lib_JPEG/jccoefct.d \
./Middlewares/Lib_JPEG/jccolor.d \
./Middlewares/Lib_JPEG/jcdctmgr.d \
./Middlewares/Lib_JPEG/jchuff.d \
./Middlewares/Lib_JPEG/jcinit.d \
./Middlewares/Lib_JPEG/jcmainct.d \
./Middlewares/Lib_JPEG/jcmarker.d \
./Middlewares/Lib_JPEG/jcmaster.d \
./Middlewares/Lib_JPEG/jcomapi.d \
./Middlewares/Lib_JPEG/jcparam.d \
./Middlewares/Lib_JPEG/jcprepct.d \
./Middlewares/Lib_JPEG/jcsample.d \
./Middlewares/Lib_JPEG/jctrans.d \
./Middlewares/Lib_JPEG/jdapimin.d \
./Middlewares/Lib_JPEG/jdapistd.d \
./Middlewares/Lib_JPEG/jdarith.d \
./Middlewares/Lib_JPEG/jdatadst.d \
./Middlewares/Lib_JPEG/jdatasrc.d \
./Middlewares/Lib_JPEG/jdcoefct.d \
./Middlewares/Lib_JPEG/jdcolor.d \
./Middlewares/Lib_JPEG/jddctmgr.d \
./Middlewares/Lib_JPEG/jdhuff.d \
./Middlewares/Lib_JPEG/jdinput.d \
./Middlewares/Lib_JPEG/jdmainct.d \
./Middlewares/Lib_JPEG/jdmarker.d \
./Middlewares/Lib_JPEG/jdmaster.d \
./Middlewares/Lib_JPEG/jdmerge.d \
./Middlewares/Lib_JPEG/jdpostct.d \
./Middlewares/Lib_JPEG/jdsample.d \
./Middlewares/Lib_JPEG/jdtrans.d \
./Middlewares/Lib_JPEG/jerror.d \
./Middlewares/Lib_JPEG/jfdctflt.d \
./Middlewares/Lib_JPEG/jfdctfst.d \
./Middlewares/Lib_JPEG/jfdctint.d \
./Middlewares/Lib_JPEG/jidctflt.d \
./Middlewares/Lib_JPEG/jidctfst.d \
./Middlewares/Lib_JPEG/jidctint.d \
./Middlewares/Lib_JPEG/jmemmgr.d \
./Middlewares/Lib_JPEG/jmemnobs.d \
./Middlewares/Lib_JPEG/jquant1.d \
./Middlewares/Lib_JPEG/jquant2.d \
./Middlewares/Lib_JPEG/jutils.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/Lib_JPEG/jaricom.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jaricom.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jaricom.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jcapimin.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jcapimin.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jcapimin.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jcapistd.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jcapistd.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jcapistd.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jcarith.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jcarith.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jcarith.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jccoefct.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jccoefct.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jccoefct.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jccolor.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jccolor.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jccolor.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jcdctmgr.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jcdctmgr.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jcdctmgr.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jchuff.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jchuff.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jchuff.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jcinit.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jcinit.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jcinit.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jcmainct.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jcmainct.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jcmainct.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jcmarker.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jcmarker.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jcmarker.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jcmaster.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jcmaster.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jcmaster.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jcomapi.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jcomapi.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jcomapi.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jcparam.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jcparam.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jcparam.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jcprepct.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jcprepct.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jcprepct.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jcsample.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jcsample.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jcsample.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jctrans.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jctrans.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jctrans.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jdapimin.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jdapimin.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jdapimin.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jdapistd.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jdapistd.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jdapistd.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jdarith.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jdarith.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jdarith.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jdatadst.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jdatadst.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jdatadst.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jdatasrc.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jdatasrc.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jdatasrc.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jdcoefct.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jdcoefct.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jdcoefct.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jdcolor.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jdcolor.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jdcolor.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jddctmgr.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jddctmgr.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jddctmgr.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jdhuff.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jdhuff.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jdhuff.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jdinput.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jdinput.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jdinput.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jdmainct.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jdmainct.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jdmainct.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jdmarker.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jdmarker.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jdmarker.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jdmaster.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jdmaster.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jdmaster.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jdmerge.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jdmerge.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jdmerge.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jdpostct.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jdpostct.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jdpostct.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jdsample.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jdsample.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jdsample.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jdtrans.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jdtrans.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jdtrans.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jerror.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jerror.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jerror.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jfdctflt.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jfdctflt.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jfdctflt.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jfdctfst.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jfdctfst.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jfdctfst.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jfdctint.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jfdctint.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jfdctint.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jidctflt.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jidctflt.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jidctflt.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jidctfst.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jidctfst.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jidctfst.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jidctint.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jidctint.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jidctint.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jmemmgr.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jmemmgr.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jmemmgr.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jmemnobs.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jmemnobs.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jmemnobs.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jquant1.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jquant1.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jquant1.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jquant2.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jquant2.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jquant2.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lib_JPEG/jutils.o: E:/GitHub_Projects_Repo/stm32f7508_projects/LibJPEG_Decoding/Middlewares/Third_Party/LibJPEG/source/jutils.c Middlewares/Lib_JPEG/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 '-DAPPLICATION_ADDRESS=0x90000000U' '-DSYSTEM_FREQ=216' -DUSE_HAL_DRIVER -DSTM32F750xx -DUSE_STM32F7508_DISCO -c -I../../../Inc -I../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32F7508-Discovery -I../../../Drivers/BSP/Components/Common -I../../../Middlewares/Third_Party/FatFs/src -I../../../Middlewares/Third_Party/FatFs/src/drivers -I../../../Middlewares/Third_Party/LibJPEG/include -I../../../Drivers/CMSIS/Include -Os -ffunction-sections -Wall -Wno-main -fstack-usage -MMD -MP -MF"Middlewares/Lib_JPEG/jutils.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

